### ISSUE TITLE
ValueError: You must specify either total_examples or total_words, for proper job parameters updationand progress calculations. The usual value is total_examples=model.corpus_count.

### ISSUE THREAD

**Issue by 2earsonly** [Edward1Chou/SentimentAnalysis#10]
ValueError: You must specify either total_examples or total_words, for proper job parameters updationand progress calculations. The usual value is total_examples=model.corpus_count.
训练模型的时候报错↑，似乎是新版的gensim要用不同的写法？应该怎么改呢

**Comment by Hnnuus** [comment]
请问怎么解决的呢
