### ISSUE TITLE
让我来给你们解释和解决为什么预测同一句话可能出现时而不同或则时而相同的结果

### ISSUE THREAD

**Issue by jcsyl** [Edward1Chou/SentimentAnalysis#5]
首先模型本身没有任何问题，在训练和测试时候都是没有问题的
错误代码：
w2indx = {v: k+1 for k, v in gensim_dict.items()}#所有频数超过10的词语的索引,(k->v)=>(v->k)
每一次预测，同一个词对应的index 发生了变化，这样造成了同一个词对应的词向量不一样。
print 一下data 就知道了
def lstm_predict(string):
      ...
    data=input_transform(string)
    data.reshape(1,-1)
    #print(data)
解决思路：
在训练词向量时候，将训练好的词对应的index 保存到文件中，预测时候拿出来用即可

**Comment by jcsyl** [comment]
各位可以去参考一下我的代码（基于作者的代码，修改少部分错误）

**Comment by hufengshuo07** [comment]
您好，您的code似乎缺少一个word2index.txt文件

**Comment by jcsyl** [comment]
@hufengshuo07  运行 lstm_train.py 时候将会生成。
